ci:
  skip:
    - pytest
    - pylint

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key
      - id: no-commit-to-branch
        name: no-commit-to-main-branch
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-github-workflows
        name: validate github workflows
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/psf/black/
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # args:
        # - "--follow-imports=silent"
        # - "--ignore-missing-imports"
        # - "--show-column-numbers"
        # - "--no-pretty"
        # - "--check-untyped-defs"
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash
        language: python
        require_serial: true
        args: ["-c", "pylint $(git ls-files '*.py')"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
