ci:
  skip:
    - pytest

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key
      - id: no-commit-to-branch
        name: no-commit-to-main-branch
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/psf/black/
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - "--line-length=120"
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile=black"
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.0a7
    hooks:
      - id: pylint
        args:
          - "--max-line-length=120"
        additional_dependencies:
          - pyspark
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        # args:
        # - "--follow-imports=silent"
        # - "--ignore-missing-imports"
        # - "--show-column-numbers"
        # - "--no-pretty"
        # - "--check-untyped-defs"
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
