services:
  spark-master:
    container_name: spark-master
    image: custom_spark
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
    volumes:
      - ./data:/opt/bitnami/spark/custom_data
      - ./src:/opt/bitnami/spark/src
      - ./jars:/opt/bitnami/spark/connectors/jars
      - spark-logs:/opt/bitnami/spark/spark-events

  spark-worker:
    image: custom_spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/opt/bitnami/spark/custom_data
      - ./src:/opt/bitnami/spark/src
      - ./jars:/opt/bitnami/spark/connectors/jars
      - spark-logs:/opt/bitnami/spark/spark-events

  spark-history-server:
    container_name: spark-history-server
    image: custom_spark
    command: bin/spark-class org.apache.spark.deploy.history.HistoryServer
    ports:
      - '18080:18080'
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ./data:/opt/bitnami/spark/custom_data
      - ./src:/opt/bitnami/spark/src
      - ./jars:/opt/bitnami/spark/connectors/jars
      - spark-logs:/opt/bitnami/spark/spark-events

  jupyter-notebook:
    container_name: jupyter-notebook
    image: custom_spark
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root --NotebookApp.token=''
    ports:
      - '8888:8888'
    volumes:
      - ./data:/opt/bitnami/spark/custom_data
      - ./src:/opt/bitnami/spark/src
      - ./jars:/opt/bitnami/spark/connectors/jars
      - spark-logs:/opt/bitnami/spark/spark-events

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  spark-logs:
  postgres-data:
  pgadmin-data:
